package report

// HTMLTemplate 定义了诊断报告的网页结构
// 使用了 Bootstrap 5 进行美化
const HTMLTemplate = `
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KubeHealer 诊断报告 - {{ .PodName }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; padding-top: 20px; }
        .card { margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .status-running { color: #198754; font-weight: bold; }
        .status-waiting { color: #ffc107; font-weight: bold; }
        .status-terminated { color: #dc3545; font-weight: bold; }
        .issue-error { border-left: 5px solid #dc3545; background-color: #fff5f5; }
        .issue-warning { border-left: 5px solid #ffc107; background-color: #fff3cd; }
        .event-icon { width: 20px; display: inline-block; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <div class="text-center mb-4">
            <h1>🚑 KubeHealer 诊断报告</h1>
            <p class="text-muted">生成时间: {{ .GenerateTime }}</p>
        </div>

        <div class="card">
            <div class="card-header bg-primary text-white">基础信息</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3"><strong>Pod 名称:</strong> {{ .PodName }}</div>
                    <div class="col-md-3"><strong>命名空间:</strong> {{ .Namespace }}</div>
                    <div class="col-md-3"><strong>所在节点:</strong> {{ .NodeName }}</div>
                    <div class="col-md-3"><strong>重启次数:</strong> <span class="badge bg-secondary">{{ .RestartCount }}</span></div>
                </div>
                <div class="mt-2">
                    <strong>当前状态:</strong> <span class="badge bg-info text-dark">{{ .Phase }}</span>
                </div>
            </div>
        </div>

        <h3>容器深度分析</h3>
        {{ range .Containers }}
        <div class="card">
            <div class="card-header d-flex justify-content-between align-items-center">
                <span>📦 容器: <strong>{{ .Name }}</strong></span>
                <span class="badge {{ if eq .State "Running" }}bg-success{{ else }}bg-warning{{ end }}">{{ .State }}</span>
            </div>
            <div class="card-body">
                <p><strong>资源配置:</strong> <code>{{ .ResourceInfo }}</code></p>
                
                {{ if .Reason }}
                <p><strong>原因:</strong> {{ .Reason }}</p>
                {{ end }}

                {{ if .Message }}
                <div class="alert alert-secondary" role="alert">
                    <strong>详细信息:</strong> {{ .Message }}
                </div>
                {{ end }}

                {{ range .Issues }}
                <div class="alert {{ if eq .Type "Error" }}issue-error{{ else }}issue-warning{{ end }}">
                    <h5 class="alert-heading">
                        {{ if eq .Type "Error" }}🛑{{ else }}⚠️{{ end }} {{ .Title }}
                    </h5>
                    {{ if .RawError }}
                    <p class="mb-1 text-muted"><small>原始报错: {{ .RawError }}</small></p>
                    {{ end }}
                    {{ if .Suggestion }}
                    <hr>
                    <p class="mb-0"><strong>💡 修复建议:</strong> {{ .Suggestion }}</p>
                    {{ end }}
                </div>
                {{ end }}
            </div>
        </div>
        {{ end }}

        <h3>最近事件 (Events)</h3>
        <div class="card">
            <div class="card-body">
                {{ if not .Events }}
                    <p class="text-muted">暂无事件记录</p>
                {{ else }}
                    <ul class="list-group list-group-flush">
                    {{ range .Events }}
                        <li class="list-group-item">{{ . }}</li>
                    {{ end }}
                    </ul>
                {{ end }}
            </div>
        </div>
        
        <footer class="text-center mt-4 mb-4 text-muted">
            <small>Generated by KubeHealer</small>
        </footer>
    </div>
</body>
</html>
`
